#!/bin/sh

###Script de génération de la table logiciels###

#Paramètres de base
DB_User="root"
DB_Password="Formation2019"
DB_Name="VenteLicences"

#Suppresion des données
mysql --user=$DB_User --password=$DB_Password $DB_Name -e "DELETE from logiciels;"

#Création des entrées logiciels
    mysql --user=$DB_User --password=$DB_Password $DB_Name -e "INSERT INTO logiciels (id, nom, prix) VALUES (1, 'Words', 15);"
    mysql --user=$DB_User --password=$DB_Password $DB_Name -e "INSERT INTO logiciels (id, nom, prix) VALUES (2, 'Excel', 35 );"
    mysql --user=$DB_User --password=$DB_Password $DB_Name -e "INSERT INTO logiciels (id, nom, prix) VALUES (3, 'Powerpoint', 20);"
    mysql --user=$DB_User --password=$DB_Password $DB_Name -e "INSERT INTO logiciels (id, nom, prix) VALUES (4, 'Vmware', 1500);"
    mysql --user=$DB_User --password=$DB_Password $DB_Name -e "INSERT INTO logiciels (id, nom, prix) VALUES (5, 'NotePad', 5);"
    mysql --user=$DB_User --password=$DB_Password $DB_Name -e "INSERT INTO logiciels (id, nom, prix) VALUES (6, 'RedHat', 75);"
    mysql --user=$DB_User --password=$DB_Password $DB_Name -e "INSERT INTO logiciels (id, nom, prix) VALUES (7, 'Windows', 125);"
    mysql --user=$DB_User --password=$DB_Password $DB_Name -e "INSERT INTO logiciels (id, nom, prix) VALUES (8, 'AIX', 90);"
    mysql --user=$DB_User --password=$DB_Password $DB_Name -e "INSERT INTO logiciels (id, nom, prix) VALUES (9, 'Ubuntu', 100);"
